 [[redirects]]
  from = "/listing/"
  to = "https://pro-api.coinmarketcap.com/v1/cryptocurrency"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200